package com.thatdot.quine.app.v2api

import scala.concurrent.Future

import sttp.apispec.Tag
import sttp.apispec.openapi.Info
import sttp.capabilities.WebSockets
import sttp.capabilities.pekko.PekkoStreams
import sttp.tapir.{EndpointInput, server}

import com.thatdot.quine.app.BuildInfo
import com.thatdot.quine.app.v2api.endpoints._
import com.thatdot.quine.routes.exts.NamespaceParameter

object V2ApiInfo {
  val info: Info = Info(
    title = "Quine API",
    version = BuildInfo.version,
    description = Some(
      """The following is autogenerated from the OpenAPI specification [`openapi.json`]({{openapi_url}})
        |and is included in Quine as fully interactive documentation. When running Quine, you can issue
        |API calls directly from the embedded documentation pages.""".stripMargin.replace('\n', ' ') + "\n\n" +
      "For docs, guides, and tutorials, please visit <https://quine.io>",
    ),
  )

  /** Canonical tag definitions for Quine OSS V2 API.
    *
    * This list is the source of truth for operation tags. Spectral's operation-tag-defined
    * rule enforces that every operation tag matches one of these. Adding a new tag here is
    * an intentional act; a typo in an endpoint's .tag() call will fail linting rather than
    * silently creating a new group.
    *
    * The order here (sorted alphabetically) controls sidebar group ordering in Stoplight Elements.
    */
  val globalTags: List[Tag] = List(
    "Administration",
    "Ingest Streams",
    "Standing Queries",
    "Graph Algorithms",
    "UI Styling",
    "Cypher Query Language",
    "Debug Node Operations",
  ).sorted.map(Tag(_))

  def endpointSequences(
    provider: V2OssEndpointProvider,
  ): List[server.ServerEndpoint[PekkoStreams with WebSockets, Future]] =
    provider.uiEndpoints ++
    provider.adminEndpoints ++
    provider.debugEndpoints ++
    provider.ingestEndpoints ++
    provider.algorithmEndpoints ++
    provider.standingQueryEndpoints ++
    provider.cypherEndpoints ++
    provider.queryWebSocketEndpoints
}

trait V2OssEndpointProvider
    extends V2UiStylingEndpoints
    with V2QuineAdministrationEndpoints
    with V2StandingEndpoints
    with V2CypherEndpoints
    with V2AlgorithmEndpoints
    with V2DebugEndpoints
    with V2IngestEndpoints
    with V2QueryWebSocketEndpoints {
  def memberIdxParameter: EndpointInput[Option[Int]]
  def namespaceParameter: EndpointInput[Option[NamespaceParameter]]
}
