package com.thatdot.quine.app.v2api

import scala.concurrent.Future

import sttp.apispec.openapi.Info
import sttp.tapir.{EndpointInput, server}

import com.thatdot.quine.app.BuildInfo
import com.thatdot.quine.app.v2api.endpoints._

object V2ApiInfo {
  val info: Info = Info(
    title = "Quine API",
    version = BuildInfo.version,
    description = Some(
      """The following is autogenerated from the OpenAPI specification `openapi.json`
        |and is included in Quine as fully interactive documentation. When running Quine, you can issue
        |API calls directly from the embedded documentation pages.""".stripMargin.replace('\n', ' ') + "\n\n" +
      "For docs, guides, and tutorials, please visit <https://quine.io>",
    ),
  )

  def endpointSequences(provider: V2OssEndpointProvider): List[server.ServerEndpoint[Any, Future]] =
    provider.uiEndpoints ++
    provider.adminEndpoints ++
    provider.debugEndpoints ++
    provider.ingestEndpoints ++
    provider.algorithmEndpoints ++
    provider.standingQueryEndpoints ++
    provider.cypherEndpoints
}

trait V2OssEndpointProvider
    extends V2UiStylingEndpoints
    with V2QuineAdministrationEndpoints
    with V2StandingEndpoints
    with V2CypherEndpoints
    with V2AlgorithmEndpoints
    with V2DebugEndpoints
    with V2IngestEndpoints {
  def memberIdxParameter: EndpointInput[Option[Int]]
  def namespaceParameter: EndpointInput[Option[String]]
}
