<div class="md-flex__cell md-flex__cell--stretch">
  <div class="md-flex__ellipsis md-header-nav__title" style="text-align:right" data-md-component="title">
    <span style="margin: 0 1em;"><a href="/docs.html">Docs</a></span>
    <span style="margin: 0 1em;"><a href="/getting_started/index.html">Getting Started</a></span>
    <span style="margin: 0 1em;"><a href="/recipes/index.html">Recipes</a></span>
    <span style="margin: 0 1em;"><a href="/about.html">About</a></span>
    <span style="margin: 0 1em;"><a href="/download.html">Download</a></span>
  </div>
</div>

