name: CI

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_scala_213:
    name: Test (Scala 2.13)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v5
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: sbt 'scala213 test'

  test_scala_212:
    name: Test (Scala 2.12)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v5
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: sbt 'scala212 test' quine/assembly quine-docs/makeSite 'scalafixAll --check'

  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v5
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: sbt scalafmtCheckAll scalafmtSbtCheck

